# Generated by Django 4.1.4 on 2023-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
